---

# This file is a YAML formatted file. YAML indenting is done in spaces not
# tabs, and whitespace is significant. If you don't stick to this, it will
# fail on provision

# These are your website, and their names plugins/themes they're
# located in. See the docs for how to define these, and what all the keys
# and options are
# Remember, whitespace is significant! Tabs and spaces mean different things
app:

  setup:
    workflow: cdk-comp/bedrock 
    wordpress: *
    env: false
    shell: false
    mu_plugins: true
    plugins: true
    theme: true
    child_theme: false
    settings: false
    extra: false
    
  env:
    app_host: webrock.digital
    
  mu_plugins:
    - name: elsd
      zip: https://raw.githubusercontent.com/elementorplus/elsd/master/elsd.php

  plugins:
    single:
      - name: classic-editor
        package: wp-cli
        ver: *
        zip: ""
      - name: duplicate-post
        package: wp-cli
        ver: *
        zip: ""
      - name: elementor
        package: wp-cli
        ver: *
        zip: ""
      - name: envato-elements
        package: wp-cli
        ver: *
        zip: ""
      - name: insert-headers-and-footers
        package: wp-cli
        ver: *
        zip: ""
      - name: svg-support
        package: wp-cli
        ver: *
        zip: ""
      - name: wordpress-seo
        package: wp-cli
        ver: *
        zip: ""
      - name: worker
        package: wp-cli
        ver: *
        zip: ""
      - name: wp-mail-smtp
        package: wp-cli
        ver: *
        zip: ""
      - name: advanced-custom-fields-pro
        package: wp-pro-club
        ver: v5.8.4
        zip: ""
      - name: elementor-pro
        package: wp-pro-club
        ver: v2.7.2
        zip: ""
      - name: wp-rocket
        package: wp-pro-club
        ver: v3.4.0.5
        zip: ""

  theme:
    name: hello-elementor
    package: wp-cli
    ver: *
    zip: ""
    
  settings:
    # Discussion
    comment_moderation: 1
    comment_registration: 1
    default_comment_status: 0
    default_pingback_flag: 0
    default_ping_status: 0
    # General
    blogdescription: DesignLS
    date_format: d/m/Y
    time_format: H:i
    timezone_string: Europe/London
    start_of_week: 0
    site_switch_language: en_US
    # Media
    large_size_h: 0
    large_size_w: 0
    medium_size_h: 0
    medium_size_w: 0
    thumbnail_crop: 0
    thumbnail_size_h: 375
    thumbnail_size_w: 375
    # Miscellaneous
    convert_smilies: false
    uploads_use_yearmonth_folders: 0
    # Permalinks
    permalink_structure: /%postname%/
    # Privacy
    blog_public: 0
    # Reading
    frontpage_name: Homepage
    page_on_front: 4
    show_on_front: page
    # User
    admin_email: dev@wrd.co.il
    admin_password: password
    admin_user: wrdadmin
    first_name: wrd
    last_name: wrd
    
  extra:
    elementor_pro_license: ""
    wp_rocket_email: ""
    wp_rocket_key: ""

  config_templates:
    workflow: default
    env: default
    mu_plugins: default
    plugins_single: default
    theme: default
    child_theme: default
    settings: default
    extra: default



